name: Sync To Gitee

on: [ push, delete, create ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@master
        env:
          # 注意在 Settings->Secrets 配置 GITEE_RSA_PRIVATE_KEY
          SSH_PRIVATE_KEY: b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZWQyNTUxOQAAACB0uTBtQ95VFOiRcCmYj4lh/H6M6yB2lhEEIlMFk8784wAAAJhwiJjtcIiY7QAAAAtzc2gtZWQyNTUxOQAAACB0uTBtQ95VFOiRcCmYj4lh/H6M6yB2lhEEIlMFk8784wAAAEBgYK5Z1Rhort52fbkbdTTvduBG2Rib0DKPhpkmgpiEinS5MG1D3lUU6JFwKZiPiWH8fozrIHaWEQQiUwWTzvzjAAAAEDM3MTg0NzU3M0BxcS5jb20BAgMEBQ== 
        with:
          # 注意替换为你的 GitHub 源仓库地址
          source-repo: https://github.com/yuyuan-wang-qq/edk2-tianocode-wyy-sync.git
          # 注意替换为你的 Gitee 目标仓库地址
          destination-repo: https://gitee.com/wyuyuan/edk2-tianocore.git
