name: Sync to Gitee
on:
  push:
    branches: [ "master", "main" ]  # 监听这些分支的推送事件
  schedule:
    - cron: "0 3 * * *"  # 可选：每天 UTC 时间 3 点自动同步（北京时间 11 点）

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取全部历史提交（避免浅克隆导致推送失败）

      - name: Mirror to Gitee
        run: |
          git remote add gitee https://${{ wyuyuan }}:${{ bd598b9b7fcdc1466868571b375b978a }}@gitee.com/wyuyuan/repo.git
          git push --force --mirror gitee  # 强制镜像推送（覆盖 Gitee 仓库）
