name: Sync To Gitee

on: # 这里是 Github Action 的触发条件
    schedule:
    - cron: '0 8 * * *' # 每日 24 点进行同步
    push:
    delete:
    create:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:

            - name: Sync yourreponame to Gitee
              uses: wearerequired/git-mirror-action@master
              env:
                  # 注意在 Settings -> Secrets 配置 GITEE_RSA_PRIVATE_KEY
                  SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
              with:
                  # 注意替换为你的 GitHub 源仓库地址
                  source-repo: git@github.com:yuyuan-wang-qq/edk2-tianocode-wyy-sync.git
                  # 注意替换为你的 Gitee 目标仓库地址
                  destination-repo: git@gitee.com:wyuyuan/edk2-tianocore.git
